apiVersion: v1
kind: Secret
metadata:
  name: a360nis360-secrets
  namespace: a360nis360
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/a360nis360?schema=public
  REDIS_URL: redis://redis:6379
